server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:restaurant_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: baaki
    password: secret
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

bytebites:
  restaurant:
    welcome-message: "Welcome to the Restaurant Service!"