server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/restaurant_db
    username: baaki
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

bytebites:
  restaurant:
    welcome-message: "Welcome to the Restaurant Service!"